apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend" .Release.Name }}
  labels:
    app: {{ printf "%s-frontend" .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ printf "%s-frontend" .Release.Name }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
